// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLLuong.Data;

#nullable disable

namespace QLLuong.Migrations
{
    [DbContext(typeof(QLLuongContext))]
    [Migration("20241025090222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLLuong.Models.ChamCong", b =>
                {
                    b.Property<int>("ChamCongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChamCongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChamCongId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGioRa")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayGioVao")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChamCongId")
                        .HasName("PK__ChamCong__9D16AF613091FEAC");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu")
                        .HasName("PK__ChucVu__D4639533225348B7");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.ChuyenMon", b =>
                {
                    b.Property<int>("MaChuyenMon")
                        .HasColumnType("int");

                    b.Property<string>("TenChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuyenMon")
                        .HasName("PK__ChuyenMo__9A6A23219205454B");

                    b.ToTable("ChuyenMon", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.DanToc", b =>
                {
                    b.Property<int>("MaDanToc")
                        .HasColumnType("int");

                    b.Property<string>("TenDanToc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDanToc")
                        .HasName("PK__DanToc__A5FA0970D34914F9");

                    b.ToTable("DanToc", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.HeSo", b =>
                {
                    b.Property<int>("MaHeSo")
                        .HasColumnType("int");

                    b.Property<double?>("HeSoLuong")
                        .HasColumnType("float");

                    b.HasKey("MaHeSo")
                        .HasName("PK__HeSo__0C16CD3D6D80D345");

                    b.ToTable("HeSo", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.KhenThuongKyLuat", b =>
                {
                    b.Property<int>("MaKtkl")
                        .HasColumnType("int")
                        .HasColumnName("MaKTKL");

                    b.Property<string>("LoaiKtkl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiKTKL");

                    b.Property<int?>("MaLyDo")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.HasKey("MaKtkl")
                        .HasName("PK__KhenThuo__4019B956708EE729");

                    b.HasIndex("MaLyDo");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("KhenThuongKyLuat", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<int?>("MaKtkl")
                        .HasColumnType("int")
                        .HasColumnName("MaKTKL");

                    b.Property<int?>("MaLuongCoBanPhanTramBh")
                        .HasColumnType("int")
                        .HasColumnName("MaLuongCoBan_PhanTramBH");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.HasKey("MaLuong")
                        .HasName("PK__Luong__6609A48D5AA62083");

                    b.HasIndex("MaKtkl");

                    b.HasIndex("MaLuongCoBanPhanTramBh");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.LuongCoBanPhanTramBh", b =>
                {
                    b.Property<int>("MaLuongCoBanPhanTramBh")
                        .HasColumnType("int")
                        .HasColumnName("MaLuongCoBan_PhanTramBH");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<double?>("PhanTramBhtn")
                        .HasColumnType("float")
                        .HasColumnName("PhanTramBHTN");

                    b.Property<double?>("PhanTramBhxh")
                        .HasColumnType("float")
                        .HasColumnName("PhanTramBHXH");

                    b.Property<double?>("PhanTramBhyt")
                        .HasColumnType("float")
                        .HasColumnName("PhanTramBHYT");

                    b.HasKey("MaLuongCoBanPhanTramBh")
                        .HasName("PK__LuongCoB__EDBBAA72C5AFCE92");

                    b.ToTable("LuongCoBan_PhanTramBH", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.LyDoKtkl", b =>
                {
                    b.Property<int>("MaLyDo")
                        .HasColumnType("int");

                    b.Property<string>("TenLyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLyDo")
                        .HasName("PK__LyDoKTKL__28E8B61EDE463E26");

                    b.ToTable("LyDoKTKL", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaChuyenMon")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanToc")
                        .HasColumnType("int");

                    b.Property<int?>("MaHeSo")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<int?>("MaTrinhDo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayVaoCongTy")
                        .HasColumnType("date");

                    b.Property<string>("NoiSinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoanNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA47443858AA");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaChuyenMon");

                    b.HasIndex("MaDanToc");

                    b.HasIndex("MaHeSo");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaTrinhDo");

                    b.ToTable("NhanVien", null, t =>
                        {
                            t.HasTrigger("update_luong_from_nv");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QLLuong.Models.NhanVienDaNghiViec", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("Cccd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaChuyenMon")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanToc")
                        .HasColumnType("int");

                    b.Property<int?>("MaHeSo")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<int?>("MaTrinhDo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNghiViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayVaoCongTy")
                        .HasColumnType("date");

                    b.Property<string>("NoiSinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoanNganHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA47D92B47D3");

                    b.ToTable("NhanVienDaNghiViec", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhongBan")
                        .HasName("PK__PhongBan__D0910CC8C4AAD809");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__Quyen__1D4B7ED4C979A184");

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.TrinhDo", b =>
                {
                    b.Property<int>("MaTrinhDo")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("TenTrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTrinhDo")
                        .HasName("PK__TrinhDo__B64C90D36890B05F");

                    b.ToTable("TrinhDo", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.UserLogin", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("Userpassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userpassword");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__UserLogi__77B2CA4788CF4ED4");

                    b.HasIndex("MaQuyen");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("QLLuong.Models.ChamCong", b =>
                {
                    b.HasOne("QLLuong.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChamCong__MaNhan__60A75C0F");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QLLuong.Models.KhenThuongKyLuat", b =>
                {
                    b.HasOne("QLLuong.Models.LyDoKtkl", "MaLyDoNavigation")
                        .WithMany("KhenThuongKyLuats")
                        .HasForeignKey("MaLyDo")
                        .HasConstraintName("FK__KhenThuon__MaLyD__04E4BC85");

                    b.HasOne("QLLuong.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("KhenThuongKyLuats")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__KhenThuon__MaNha__03F0984C");

                    b.Navigation("MaLyDoNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QLLuong.Models.Luong", b =>
                {
                    b.HasOne("QLLuong.Models.KhenThuongKyLuat", "MaKtklNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaKtkl")
                        .HasConstraintName("FK__Luong__MaKTKL__05D8E0BE");

                    b.HasOne("QLLuong.Models.LuongCoBanPhanTramBh", "MaLuongCoBanPhanTramBhNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaLuongCoBanPhanTramBh")
                        .HasConstraintName("FK__Luong__MaLuongCo__6477ECF3");

                    b.HasOne("QLLuong.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__Luong__MaNhanVie__6383C8BA");

                    b.Navigation("MaKtklNavigation");

                    b.Navigation("MaLuongCoBanPhanTramBhNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QLLuong.Models.NhanVien", b =>
                {
                    b.HasOne("QLLuong.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK__NhanVien__MaChuc__59FA5E80");

                    b.HasOne("QLLuong.Models.ChuyenMon", "MaChuyenMonNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChuyenMon")
                        .HasConstraintName("FK__NhanVien__MaChuy__5CD6CB2B");

                    b.HasOne("QLLuong.Models.DanToc", "MaDanTocNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaDanToc")
                        .HasConstraintName("FK__NhanVien__MaDanT__59063A47");

                    b.HasOne("QLLuong.Models.HeSo", "MaHeSoNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaHeSo")
                        .HasConstraintName("FK__NhanVien__MaHeSo__5DCAEF64");

                    b.HasOne("QLLuong.Models.PhongBan", "MaPhongBanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK__NhanVien__MaPhon__5AEE82B9");

                    b.HasOne("QLLuong.Models.TrinhDo", "MaTrinhDoNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTrinhDo")
                        .HasConstraintName("FK__NhanVien__MaTrin__5BE2A6F2");

                    b.Navigation("MaChucVuNavigation");

                    b.Navigation("MaChuyenMonNavigation");

                    b.Navigation("MaDanTocNavigation");

                    b.Navigation("MaHeSoNavigation");

                    b.Navigation("MaPhongBanNavigation");

                    b.Navigation("MaTrinhDoNavigation");
                });

            modelBuilder.Entity("QLLuong.Models.UserLogin", b =>
                {
                    b.HasOne("QLLuong.Models.NhanVien", "MaNhanVienNavigation")
                        .WithOne("UserLogin")
                        .HasForeignKey("QLLuong.Models.UserLogin", "MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__UserLogin__MaNha__59C55456");

                    b.HasOne("QLLuong.Models.Quyen", "MaQuyenNavigation")
                        .WithMany("UserLogins")
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK__UserLogin__MaQuy__5AB9788F");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("QLLuong.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLLuong.Models.ChuyenMon", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLLuong.Models.DanToc", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLLuong.Models.HeSo", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLLuong.Models.KhenThuongKyLuat", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("QLLuong.Models.LuongCoBanPhanTramBh", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("QLLuong.Models.LyDoKtkl", b =>
                {
                    b.Navigation("KhenThuongKyLuats");
                });

            modelBuilder.Entity("QLLuong.Models.NhanVien", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("KhenThuongKyLuats");

                    b.Navigation("Luongs");

                    b.Navigation("UserLogin");
                });

            modelBuilder.Entity("QLLuong.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLLuong.Models.Quyen", b =>
                {
                    b.Navigation("UserLogins");
                });

            modelBuilder.Entity("QLLuong.Models.TrinhDo", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
